# Generated by Django 5.2.6 on 2025-09-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('snack', 'Snacks')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('visitor_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
